### ISSUE TITLE
Server crashes on symbolic links (Path must be a string)

### ISSUE THREAD

**Issue by divmgl** [nbluis/static-server#19]
``` bash
$ mkdir ~/test/ && cd ~/test/
$ jspm init
$ ln -s jspm_packages/system.js system.js
$ touch index.html
```

``` html
<!-- index.html -->
<html>
<body>
<script src="system.js"></script>
<script src="config.js"></script>
</body>
</html>
```

``` bash
$ static-server --follow-symlink
```

Crashes on navigating to `index.html`:

```
$ static-server --follow-symlink

* Static server successfully started.
* Serving files at: http://localhost:9080
* Press Ctrl+C to shutdown.
<-- [GET] /
--> 200 OK / (index.html) 190 Byte (10.451ms)
<-- [GET] /system.js
<-- [GET] /config.js
* Shutting down server

path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.relative (path.js:496:3)
    at StaticServer.<anonymous> (/usr/local/lib/node_modules/static-server/bin/static-server.js:55:115)
    at emitOne (events.js:90:13)
    at StaticServer.emit (events.js:182:7)
    at /usr/local/lib/node_modules/static-server/server.js:249:22
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by yanickrochon** [comment]
This irony is that the faulty code is the "[default logger](https://github.com/nbluis/static-server/commit/170da5981080dc897b2e8ae1ef8329565b84f177#diff-ff0f5a9c61769f8c30340b66086c5659L53)".

```js
 server.on('symbolicLink', function (link, file) {
   console.log(chalk.cyan('---'), '"' + path.relative(server.rootPath, link) + '"', chalk.magenta('>'), '"' + path.relative(server.rootPath, file) + '"');
 });
```

**Comment by yanickrochon** [comment]
This [line](https://github.com/nbluis/static-server/commit/670cb7d21631d4a20b86f18938c119c6383d844a#diff-78c12f5adc1848d13b1c6f07055d996eL248)

```js
server.emit('symbolicLink', fileRef);
```

should be

```js
server.emit('symbolicLink', fileRef, file);
```

**Comment by divmgl** [comment]
@yanickrochon would you like open to a pull request for this change?

**Comment by c0b** [comment]
seems hit by this issue; I could use hard links instead (on Linux server) but why is this closed without a fix? @divmgl ?? if @nbluis no longer maintains it, would somebody like to maintain a fork?
