### ISSUE TITLE
Server crashes when given invalid range

### ISSUE THREAD

**Issue by JanPokorny** [nbluis/static-server#23]
When the server receives invalid Range, it crashes with the following error:

```
        res.headers['Content-Range'] = 'bytes=0-' + originalSize;
        ^
ReferenceError: res is not defined
    at parseRanges (C:\Users\JP\AppData\Roaming\npm\node_modules\static-server\server.js:364:9)
    at sendFile (C:\Users\JP\AppData\Roaming\npm\node_modules\static-server\server.js:446:22)
    at C:\Users\JP\AppData\Roaming\npm\node_modules\static-server\server.js:169:9
    at C:\Users\JP\AppData\Roaming\npm\node_modules\static-server\server.js:275:9
    at FSReqWrap.oncomplete (fs.js:95:15)
```

It seems like the function for parsing ranges isn't passed the `res` variable.

**Comment by olalonde** [comment]
Also had this issue:

```
 * Shutting down server

 /app/node_modules/static-server/server.js:364
         res.headers['Content-Range'] = 'bytes=0-' + originalSize;
         ^

 ReferenceError: res is not defined
     at parseRanges (/app/node_modules/static-server/server.js:364:9)
     at sendFile (/app/node_modules/static-server/server.js:446:22)
     at /app/node_modules/static-server/server.js:169:9
     at /app/node_modules/static-server/server.js:275:9
     at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by olalonde** [comment]
Just sent a PR that will hopefully fix this.
